### ISSUE TITLE
Using Chromium installed by snap results in "Timed out after 30000 ms while trying to connect to Base!"

### ISSUE THREAD

**Issue by Xeevis** [hardkoded/puppeteer-sharp#1581]
Hello I have trouble getting latest Puppeteer-sharp to connect to snap chromium instance.

On Ubuntu 20.04.1 LTS Server I've installed Chromium via

    sudo snap install chromium

And try to launch it in code with

    await Puppeteer.LaunchAsync(new LaunchOptions() { ExecutablePath = "/snap/bin/chromium"});

![image](https://user-images.githubusercontent.com/5835044/97971805-e4d62600-1dc3-11eb-8f6b-c348c9b2955b.png)

While it appears Chromium runs correctly, it won't connect to it, timing out after 30 seconds with 
> Timed out after 30000 ms while trying to connect to Base!

Any idea how to get this working? Thanks.

Note: Local instance downloaded to .local-chromium works fine, perhaps new Chromium releases aren't supported?

**Comment by ullas1989** [comment]
Hi, is there any update on this issue? I am having same for Windows 10.

**Comment by Xeevis** [comment]
> Hi, is there any update on this issue? I am having same for Windows 10.

I gave up trying to get it to work with browser directly, I've solved it much more elegantly with [Browserless service](https://github.com/browserless/chrome) running in docker. It has many benefits, it can scale, blocks ads, stable, handles crashes, works with latest version and manages instances with parallelism and queueing and more because clients consume it through web socket instead of managing it's process.

Quick steps to set it up

1. Install docker
```bash
sudo snap install docker
```
2. Create file $home/docker-compose.yml

```yml
version: '3.8'
services:
  browser:
    container_name: browserless_chrome
    image: browserless/chrome
    restart: always
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=5
      - MAX_QUEUE_LENGTH=5
      - FUNCTION_ENABLE_INCOGNITO_MODE=true
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - CHROME_REFRESH_TIME=3600000
      - WORKSPACE_DELETE_EXPIRED=true
      - WORKSPACE_EXPIRE_DAYS=7
      - ENABLE_DEBUGGER=false
      - EXIT_ON_HEALTH_FAILURE=true
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_LAUNCH_ARGS=["--window-size=1920,1080", "--lang=en-US,en;q=0.9"]
      - DEFAULT_IGNORE_HTTPS_ERRORS=false
```

Make sure to secure the port with firewall and run the container
```bash
sudo docker-compose -f $home/docker-compose.yml up -d
```

Then connect to it with your client
```csharp
var remoteHeadlessBrowser = await Puppeteer.ConnectAsync(new ConnectOptions() 
{
    BrowserWSEndpoint = "ws://localhost:3000", 
    IgnoreHTTPSErrors = true 
});
```
